apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: practice-js-hpa
  namespace: agility-${DEPLOY_ENV}-env
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: practice-js-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
